/* To avoid CSS expressions while still supporting IE 7 and IE 6, use this script */
/* The script tag referencing this file must be placed before the ending body tag. */

/* Use conditional comments in order to target IE 7 and older:
	<!--[if lt IE 8]><!-->
	<script src="ie7/ie7.js"></script>
	<!--<![endif]-->
*/

(function() {
	function addIcon(el, entity) {
		var html = el.innerHTML;
		el.innerHTML = '<span style="font-family: \'RamadaIconFont\'">' + entity + '</span>' + html;
	}
	var icons = {
		'icon-pool': '&#xe900;',
		'icon-training': '&#xe901;',
		'icon-term': '&#xe902;',
		'icon-area-stroke': '&#xe903;',
		'icon-rooms': '&#xe904;',
		'icon-events-dva-restorana-2': '&#xe905;',
		'icon-events-residence': '&#xe906;',
		'icon-events-garderob': '&#xe907;',
		'icon-events-lounge': '&#xe908;',
		'icon-events-parkovka-2': '&#xe909;',
		'icon-events-spa': '&#xe90a;',
		'icon-star-menu': '&#xe90b;',
		'icon-share-fill': '&#xe90c;',
		'icon-mobile-bar': '&#xe90d;',
		'icon-gastro-dinner': '&#xe90e;',
		'icon-master-classes': '&#xe90f;',
		'icon-headset': '&#xe910;',
		'icon-catering-main': '&#xe911;',
		'icon-photographer': '&#xe912;',
		'icon-decorator': '&#xe913;',
		'icon-tech-support': '&#xe914;',
		'icon-video-conference': '&#xe915;',
		'icon-catering': '&#xe916;',
		'icon-lcd-panel': '&#xe917;',
		'icon-notebooks-pens': '&#xe918;',
		'icon-podium': '&#xe919;',
		'icon-plasma-tv-stand': '&#xe91a;',
		'icon-water': '&#xe91b;',
		'icon-laser-pointer': '&#xe91c;',
		'icon-gooseneck-mic': '&#xe91d;',
		'icon-clicker': '&#xe91e;',
		'icon-laptop': '&#xe91f;',
		'icon-flipchart': '&#xe920;',
		'icon-microphone': '&#xe921;',
		'icon-sound-system': '&#xe922;',
		'icon-projector': '&#xe923;',
		'icon-screen': '&#xe924;',
		'icon-hair-dryer': '&#xe925;',
		'icon-toiletries': '&#xe926;',
		'icon-shower-cabin': '&#xe927;',
		'icon-aqua-zone': '&#xe928;',
		'icon-bathrobe': '&#xe929;',
		'icon-washing-machine': '&#xe92a;',
		'icon-tableware': '&#xe92b;',
		'icon-kettle': '&#xe92c;',
		'icon-microwave': '&#xe92d;',
		'icon-cooktop': '&#xe92e;',
		'icon-fridge': '&#xe92f;',
		'icon-sofa-bed': '&#xe930;',
		'icon-iron-board': '&#xe931;',
		'icon-air-conditioner': '&#xe932;',
		'icon-work-area': '&#xe933;',
		'icon-wi-fi': '&#xe934;',
		'icon-tv': '&#xe935;',
		'icon-single-beds': '&#xe936;',
		'icon-double-bed': '&#xe937;',
		'icon-max': '&#xe938;',
		'icon-events-tri-konferens-zala': '&#xe939;',
		'icon-events-special-tariffs': '&#xe93a;',
		'icon-events-prostornye-nomera': '&#xe93b;',
		'icon-events-parkovka': '&#xe93c;',
		'icon-events-personal-manager': '&#xe93d;',
		'icon-events-raspolozhenie': '&#xe93e;',
		'icon-events-avtorkaya-kuhnya': '&#xe93f;',
		'icon-events-panoramnye-okna': '&#xe940;',
		'icon-events-basseyn': '&#xe941;',
		'icon-events-infrastructura': '&#xe942;',
		'icon-events-vremya': '&#xe943;',
		'icon-events-catering': '&#xe944;',
		'icon-events-banketnoe-menu': '&#xe945;',
		'icon-events-dva-restorana': '&#xe946;',
		'icon-events-razmeshcheniye-gostey': '&#xe947;',
		'icon-events-territoriya': '&#xe948;',
		'icon-gis-icon': '&#xe94a;',
		'icon-share': '&#xe94b;',
		'icon-copy-fill': '&#xe94c;',
		'icon-person': '&#xe94d;',
		'icon-d': '&#xe94f;',
		'icon-area': '&#xe950;',
		'icon-arrow-left': '&#xe951;',
		'icon-arrow-right': '&#xe952;',
		'icon-book': '&#xe953;',
		'icon-burger': '&#xe954;',
		'icon-caplya': '&#xe955;',
		'icon-chevron-down': '&#xe957;',
		'icon-chevron-left': '&#xe958;',
		'icon-chevron-link': '&#xe959;',
		'icon-chevron-right': '&#xe95a;',
		'icon-chevron-top': '&#xe95b;',
		'icon-close': '&#xe95c;',
		'icon-delovoy': '&#xe95d;',
		'icon-elem-bed': '&#xe95e;',
		'icon-elem-phen': '&#xe95f;',
		'icon-elem-pool': '&#xe960;',
		'icon-elem-tablichka': '&#xe961;',
		'icon-family': '&#xe962;',
		'icon-friends': '&#xe963;',
		'icon-geo': '&#xe964;',
		'icon-mail': '&#xe965;',
		'icon-menu': '&#xe966;',
		'icon-para': '&#xe967;',
		'icon-pdf': '&#xe968;',
		'icon-places': '&#xe969;',
		'icon-play': '&#xe96a;',
		'icon-route': '&#xe96b;',
		'icon-services-board': '&#xe96c;',
		'icon-services-coffee-machine': '&#xe96d;',
		'icon-services-condicioner': '&#xe96e;',
		'icon-services-electric-kettle': '&#xe96f;',
		'icon-services-garderob': '&#xe970;',
		'icon-services-holodilnik': '&#xe971;',
		'icon-services-kids-bedroom': '&#xe972;',
		'icon-services-master-bedroom': '&#xe973;',
		'icon-services-microwave': '&#xe974;',
		'icon-services-places': '&#xe975;',
		'icon-services-tv': '&#xe976;',
		'icon-services-wifi': '&#xe977;',
		'icon-solo': '&#xe978;',
		'icon-star': '&#xe979;',
		'icon-telegram': '&#xe97a;',
		'icon-vk': '&#xe97b;',
		'icon-whatsapp': '&#xe97c;',
		'0': 0
		},
		els = document.getElementsByTagName('*'),
		i, c, el;
	for (i = 0; ; i += 1) {
		el = els[i];
		if(!el) {
			break;
		}
		c = el.className;
		c = c.match(/icon-[^\s'"]+/);
		if (c && icons[c[0]]) {
			addIcon(el, icons[c[0]]);
		}
	}
}());
